[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/greatsong/Desktop/2018pycon
[NotebookApp | INFO] 0 active kernels 
[NotebookApp | INFO] The Jupyter Notebook is running at: http://localhost:8888/?token=85d21107531a3cb4c31c385fc844bac9d0caf5e9586e5fe3
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=85d21107531a3cb4c31c385fc844bac9d0caf5e9586e5fe3
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/greatsong/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] Notebook 파이썬 병아리반(180801).ipynb is not trusted
[NotebookApp | INFO] Kernel started: ae279ef8-b5fd-4828-9fa8-c467cae4b0d8
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down kernels
[NotebookApp | INFO] Kernel shutdown: ae279ef8-b5fd-4828-9fa8-c467cae4b0d8
